[toolchain]
package_manager = "pnpm"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stablecoin = "2V3QeeZGXpghj7PTHVftMAQhxX5GEZYf5EoiWHDtLhhF"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 \"tests/**/*.test.ts\""

[test]
startup_wait = 10000
shutdown_wait = 2000
upgradable = false

[test.validator]
# bind_address = "0.0.0.0"
bind_address = "127.0.0.1"
url = "https://api.mainnet-beta.solana.com"
# url = "https://api.devnet.solana.com"
ledger = ".anchor/test-ledger"
rpc_port = 8899

[[test.validator.clone]]
address = "metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s" # implicitly also clones PwDiXFxQsGra4sFFTT8r1QWRMd4vfumiWC1jfWNfdYT

# Pyth SOL/USD Price Feed (devnet)
# [[test.validator.clone]]
# address = "7UVimffxr9ow1uXYxsr4LHAcV58mLzhmwaeKvJ1pjLiE"
